language: python
python:
  - "2.7"
#    env: TEST_SUITE=groupwise-2.0
# command to install dependencies
install:
  - pip install -r ./groupwise-2.0/requirements.txt
# command to run tests
script: py.test ./groupwise-2.0/*
